spring:
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: email@email.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
