spring:
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: vit.vassarotti@outlook.it
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true